### ISSUE TITLE
Alguem com esse problema? @vendor/rfs

### ISSUE THREAD

**Issue by speednowintegracao** [twbs/bootstrap-npm-starter#107]
![image](https://user-images.githubusercontent.com/104096852/217561561-db10ae24-fd24-4310-b2dd-7d2d4694a883.png)

**Comment by julien-deramond** [comment]
Could you please provide more information regarding your environment?
From what I see in these logs, you're using `bootstrap-npm-starter@1.4.0`, could you try with the [latest version](https://github.com/twbs/bootstrap-npm-starter/releases/tag/v2.0.0)?

**Comment by speednowintegracao** [comment]
> Você poderia fornecer mais informações sobre o seu ambiente? Pelo que vejo nesses logs, você está usando `bootstrap-npm-starter@1.4.0`, poderia tentar com a [versão mais recente](https://github.com/twbs/bootstrap-npm-starter/releases/tag/v2.0.0) ?

Don't have a ready-made version of the latest bootstrap, or know how to update?
