### ISSUE TITLE
make a cli tools like 'create-react-app'

### ISSUE THREAD

**Issue by jamal-pb95** [twbs/bootstrap-npm-starter#20]
Hello, can you please make a cli tool like 'create-react-app' to start a bootstrap project scaffold from cli.

**Comment by HansUXdev** [comment]
I used to maintain a private fork of foundation's cli and I wouldn't mind teaming up with people on this.
However, CLI's are a lot of work to build and maintain...

Personally, I'd rather team up and build a feature rich extension for vscode to accomplish the same things.
[MJML](https://marketplace.visualstudio.com/items?itemName=attilabuti.vscode-mjml) is a good example of what i mean, 
it has a built in preview of markup, and fetch official [example templates](https://getbootstrap.com/docs/5.0/examples/), but adding a search feature for community driven templates (similar to [CRA templates](https://www.npmjs.com/search?q=cra-template-*)) shouldn't be that hard either.

**Comment by jamal-pb95** [comment]
Thanks @HansUXdev

**Comment by HansUXdev** [comment]
No problem @jamal-pb95. In the meantime, if you use bootstrap 5 and vscode, you may be interested in collaborating on the [extension I maintain](https://marketplace.visualstudio.com/items?itemName=HansUXdev.bootstrap5-snippets). 
It's not very hard compared to a full CLI and just wraps snippets (including the example templates) of html, css, js inside json.

I've been meaning to look into upgrading it to a full extension and not just snippets by adding the [command api](https://code.visualstudio.com/api/extension-guides/command) and [webview api](https://code.visualstudio.com/api/extension-guides/webview).
