### ISSUE TITLE
update for v5

### ISSUE THREAD

**Issue by HansUXdev** [twbs/bootstrap-npm-starter#35]
I'm working on a PR right now to deal address the other issues and PR's that haven't been approved and wanted to clearify a few things.

@mdo what are the overall goals of this template?
Is it meant to only support only v4 / is there any opposition to updating to the v5 (beta1 currently)?
Would there be any opposition to a massive PR, or does the bootstrap team prefer single issue PR's?

Example of a massive PR:
- uses v5
- add livereload  #21
- and improve scripts with npm #22 to have npm start, babel, lint, post-css, etc
- add support for gitpod and or codespaces (try this repo out in the browser)
- add optional vscode extension recommendation
- Update Documentation to reflect the above

Some people have compared this to CRA, however, I really like the fact that the template doesn't hide the tooling like CRA.
Personally, I see this as a great resource for beginners to learn bootstrap and would like to improve it.

**Comment by mdo** [comment]
Any help here would be very much appreciated! Definitely want to include v5 in this with a new tagged release. A single massive PR would be a little difficult to manage though. Any chance we could break things down into smaller PRs?

**Comment by HansUXdev** [comment]
I'm not opposed to that. This is the fork I'm working on: https://github.com/HansUXdev/bootstrap-npm-starter/tree/v5-beta

I started it by adding most, if not everything from the existing PR's because those are small changes involving packages, or adding config files for webpack and linting. In terms of breaking it down to smaller PR's, would this be the best starting point?

I'm fine reverting back to the point mentioned above.
In later commits, I introduced major changes  such as moving the scss folder into assets and reworking the npm scripts.

My goal with the later commits was to have two main task, `npm start` for development with live reload and unminified css & js and a separate production task that minifies and bundles it all.

I have webpack working to compile javascript and provide a live reload via webpack cli, but it doesn't currently reference the webpack file. I also still need to test the JavaScript components in dev and production mode. 
I've made detail commits and updated the documentation accordingly.

**Comment by HansUXdev** [comment]
> Any help here would be very much appreciated! Definitely want to include v5 in this with a new tagged release. A single massive PR would be a little difficult to manage though. Any chance we could break things down into smaller PRs?

I'm not opposed to that. 
I started it by adding most, if not everything from the existing PR's because those are small changes involving packages, or adding config files for webpack and linting. In terms of breaking it down to smaller PR's, would this be the best starting point? So I'm fine reverting back to the point because it should bring the repo to current.

This is the fork I'm working on: 
https://github.com/HansUXdev/bootstrap-npm-starter/tree/v5-beta

I've made detail commits and updated the readme accordingly.
In later commits, I introduced major changes  such as moving the scss folder into assets and reworking the npm scripts.

My goal with the later commits was to have two main task, `npm start` for development with live reload and unminified css & js and a separate production task that minifies and bundles it all.

I have webpack working to compile javascript and provide a live reload via webpack cli, but it doesn't currently reference the webpack file. I also still need to test the JavaScript components in dev and production mode.

**Comment by bardware** [comment]
I came here throught the bootstrap 5 site and was surprised this project still uses node-sass according to the package.json

**Comment by kanlukasz** [comment]
When will the official launch of the starter for v5 take place?

**Comment by RobJacobson** [comment]
I'm new to Bootstrap.  I naturally want to play with the "latest and greatest" version, so this repo doesn't currently meet my expectations/needs.

There seems to have been a pending pull request for several months.  Any chance this could be integrated/finished?

**Comment by mandrasch** [comment]
I built a simple starter repo with eleventy framework, maybe useful while waiting :-)
https://mandrasch.github.io/11ty-plain-bootstrap5/
