### ISSUE TITLE
Position to overwrite the default variables

### ISSUE THREAD

**Issue by marvinhuebner** [twbs/bootstrap-npm-starter#42]
As described in the `starter.scss` file, the default variables should be imported first and then I can overwrite them.

But if I want to set for example the global border radius (`$border-radius`) to 0, then I have to overwrite all variables where `$border-radius` is referenced.

```scss
@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/mixins";

//
// Override Bootstrap here 
//

// Overwriting `$primary` has no effect here
$primary: red;

$border-radius: 0;
$btn-border-radius: 0;
$card-border-radius: 0;

@import "bootstrap/scss/reboot";
@import "bootstrap/scss/buttons";
@import "bootstrap/scss/card";
```

Wouldn't it be better to overwrite the variables before importing the default variables? So I only have to overwrite `$border-radius: 0;`and it is taken over for all references? The same applies to colors, I have included the primary color as an example.

```scss
$border-radius: 0;
$primary: red;

@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/mixins";

@import "bootstrap/scss/reboot";
@import "bootstrap/scss/buttons";
@import "bootstrap/scss/card";
```

Maybe there is some special reason that the default variables are imported first? 

I have created a small demo here for you to see how it works: https://codesandbox.io/s/bootstrap-variable-overwrites-btirk?file=/src/styles.scss

Thanks for your input in advance!

**Comment by mdo** [comment]
The way Sass works unfortunately, you need to do it after the variables for it to work properly with all variable and maps. Check out this Sassmeister as an example: https://www.sassmeister.com/gist/851211cbbbd6c72969ec9bdd946d31a2.

The default variables and maps aren't properly overwritten until you put the replacement values after the `!default`s.

**Comment by marvinhuebner** [comment]
Ok, for maps I understand that. 

But then what is the recommended way to globally override the primary color, for example? 

This must actually be done before the default variables. I've updated my codesandbox for an example: https://codesandbox.io/s/bootstrap-variable-overwrites-btirk?file=/src/styles.scss

You can also find a simplified example here: https://www.sassmeister.com/gist/3e8855f62d020ecf7bd4820d609fd98d
