### ISSUE TITLE
Add Action to push built site as a live site

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap-npm-starter#47]
- Add Action to build and deploy the site
- Push it to a new `gh-pages` branch
- Trigger event should be a release
- Add CNAME for `npm.getbootstrap.com`

/cc @XhmikosR in case you have preferences or ideas

**Comment by XhmikosR** [comment]
My only concern is that right now we serve basically everything from the root dir, which isn't ideal. That being said, the rest should be easy to do.

**Comment by mdo** [comment]
We can address that too. Maybe bump to v2 for that?

**Comment by XhmikosR** [comment]
I think I can do both by just including a deploy script and copying what we need to be in dist. I just need to find some time :)

I'll try to do this in the next days.
