### ISSUE TITLE
Bootstrap 5.0.1 and Angular 12

### ISSUE THREAD

**Issue by hugoebarboza** [twbs/bootstrap-npm-starter#55]
Is there guidance to install bootstrap with Angular 12 ?

Recently, I upgrade my Angular project to Bootstrap 5 but all bootstrap functionality crashed.

**Comment by mdo** [comment]
Closing as a duplicate of https://github.com/twbs/bootstrap/discussions/34127. This is an npm starter project that doesn't use Angular, so I can't help you there.

**Comment by hugoebarboza** [comment]
Hi @mdo, but Bootstrap 5 supports Angular ?
