### ISSUE TITLE
npm ERR! missing script: css-compile

### ISSUE THREAD

**Issue by dnguyencode** [twbs/bootstrap-npm-starter#60]
Hi, 
I can't start this project due to this error. 
I tried to run 
npm install -g css-compile but no such component exist.
I'm running node 6.14.13 on windows.

**Comment by djKianoosh** [comment]
@dnguyencode see the Usage section in the readme: https://github.com/twbs/bootstrap-npm-starter#usage

The command is `npm run css-compile`, not `install -g`
