### ISSUE TITLE
Build Steps and configuration for Cloudflare Pages integration

### ISSUE THREAD

**Issue by henkisdabro** [twbs/bootstrap-npm-starter#72]
I read through the README, and tried to understand how I could prepare a project built from this template to work with "Cloudflare Pages". They have guides for common frameworks but not Bootstrap, so I was hoping to get assistance here on the best approach? Do we continue to use github Actions for the stylelint, or is done by the build step by Cloudflare Pages build environment after pulling in the repo? Grateful for any guidance! Here's the [Cloudflare Pages documentation for a Gatsby site](https://developers.cloudflare.com/pages/framework-guides/deploy-a-gatsby-site)

**Comment by mdo** [comment]
This is outside the scope of this repo, and I'm planning to archive this project in favor of https://github.com/twbs/examples.
