### ISSUE TITLE
config file and autoload

### ISSUE THREAD

**Issue by paulrajib** [twbs/bootstrap-npm-starter#74]
How can we get a config file like webpack.config.js or babel.config.js file so we don't have to put full path like 
e.g: 
import "../../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js";
just import "bootstrap.bundle.min.js"; should be okay and again having issue with import '../../node_modules/@popperjs/core';
Please have a look and let us know.

**Comment by mdo** [comment]
Please see https://github.com/twbs/examples.
