### ISSUE TITLE
Purge CSS issues

### ISSUE THREAD

**Issue by marko-lazovic** [twbs/bootstrap-npm-starter#77]
Hello, 
I've created one small website using this starter template and I have two issues regarding the CSS Purge part:

1. I can't locate purgecss.config.js file. I have to make some tweaks to the default purge css configuration because I have more pages than just index.html. Can you please tell me where can I find the default config file for the purge css?
2. When css is purged on index.html, Bootstrap Carousel slide animation stops to work. It still does change slides though, but without any animation, just static change of slides. Any ideas what's missing?

Thank you.

**Comment by mdo** [comment]
We don't have a Purge CSS config—that's all done via CLI params. For JS, you'll have to pass in an approved list of classes to keep around that can only be found in JS. There are plenty of guides for this already, so I won't go into it here. Best of luck!
