### ISSUE TITLE
Issue with node version 16

### ISSUE THREAD

**Issue by GwaraDon** [twbs/bootstrap-npm-starter#86]
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
 npm WARN old lockfile so supplemental metadata must be fetched from the registry. 
npm WARN old lockfile npm WARN old lockfile This is a one-time fix-up, please be patient... npm WARN old lockfile

**Comment by python-coding-404** [comment]
me too

**Comment by thecodedabbler** [comment]
Having the same issue. Had to install old version to make it work.

**Comment by kater-mult** [comment]
Just had the same issue on node v14.18.2

**Comment by ItsDanielHarris** [comment]
Experiencing the same issue here. Also it gets stuck on installing the dependency stylelint.
