### ISSUE TITLE
Add Gulp

### ISSUE THREAD

**Issue by ayoubkhan558** [twbs/bootstrap-npm-starter#93]
Why not add Gulp https://gulpjs.com/ into workflow?

**Comment by mdo** [comment]
Gulp isn't strictly necessary and adds another set of dependencies. This repo may also get archived soon depending on the work happening in https://github.com/twbs/examples. And we could theoretically do a Gulp example there. Maybe open an issue there to add a Gulp example and we'll see where it goes?
